version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
            - ./.docker/log/nginx:/var/log/nginx
        ports:
            - ${PORT}:80
        restart: always
        depends_on:
            - php
        links:
            - php
    php:
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html
        depends_on:
            - db
        links:
            - db
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
    db:
        image: postgres:14.9
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
            - ./database/dumps/:/var/dumps/
